import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
                    <header className='header-main'>
                
                  {/* Logo */}
                  <a href="/" className="header-main-logo">
                      <img src="" className="h-8" alt="BookStore Logo" />
                      <span className="">BookStore</span>
                  </a>

                  {/* Navigation s */}
                    <Link href="/">Home</Link>
                    <Link href="/about">About</Link>
                    <Link href="/login">Login</Link>
                    <Link href="/books">Explore Books</Link>
                    <Link href="/book/create">Create Book</Link>
            </header>
        {children}
      </body>
    </html>
  );
}
